### ISSUE TITLE
Procedure include stopping services. This step may not be necessary

### ISSUE THREAD

**Issue by ahmadm-netapp** [NetAppDocs/storagegrid-117#12]
### Page URL

https://docs.netapp.com/us-en/storagegrid-117/maintain/shutting-down-grid-node.html

### Page title

Shut down grid node

### Summary

In previous discussions, we were updated that manually stopping services is not necessary. Shutdown command would also stop services.

Should this page be updated to remove stopping services step?

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-pcarriga** [comment]
Hi @ahmadm-netapp, thanks for this suggestion. I'll verify and update the documentation accordingly.
