### ISSUE TITLE
Invalid JSON example

### ISSUE THREAD

**Issue by scaleoutsean** [NetAppDocs/storagegrid-117#15]
### Page URL

https://docs.netapp.com/us-en/storagegrid-117/tenant/json-generated-by-search-integration-service.html

### Page title

JSON generated by search integration service

### Summary

The JSON is invalid

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-pcarriga** [comment]
Hi @scaleoutsean, thanks for highlighting this issue. I'll verify the correct JSON file and update the documentation accordingly.
