### ISSUE TITLE
About Node Cloning, wordings changed in 11.7 compared to 11.5/11.6. Is it intentional?

### ISSUE THREAD

**Issue by ntap-leeray** [NetAppDocs/storagegrid-117#22]
### Page URL

https://docs.netapp.com/us-en/storagegrid-117/commonhardware/how-appliance-node-cloning-works.html

### Page title

Appliance node cloning: Overview

### Summary

In 11.7, it says: "If the target storage appliance has the same number of drives as the source node, the drives in the target appliance **_must have greater capacity_** (in TB)."

In both 11.5 and 11.6, it says: "If the target storage appliance has the same number of drives as the source node, the drives in the target appliance must have the **_same capacity (in TB) or larger_**."

The above were from the Overview session related Node Cloning. In the next section which is titled "Consideration and Requirement for Appliance Node Cloning", now 11.5 is the one that says "same or greater" where 11.6 and 11.7 agree with one another and say "greater". 

One way or another, we need to synchronize these docs (and various mentions of the same information). Thanks.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-pcarriga** [comment]
Hi @ntap-leeray, thanks for highlighting this difference between the versions. I'll work with the StorageGRID team to confirm what is correct. Thanks!

**Comment by netapp-pcarriga** [comment]
Hi @ntap-leeray, we've updated the StorageGRID 11.6 documentation to align with versions 11.7 and 11.8. At this stage, we will not be updating version 11.5. 

Thanks again for bringing this to our attention.
