### ISSUE TITLE
Can this page be streamlined?

### ISSUE THREAD

**Issue by netapp-aronk** [NetAppDocs/storagegrid-117#23]
### Page URL

https://docs.netapp.com/us-en/storagegrid-117/storagegrid-enable.html

### Page title

How to enable StorageGRID in your environment

### Summary

Can we streamline this page to make it more obvious to click the link to go to the enablement site?  probably do not need all the extra text other than Click here to go to the site.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-maireadn** [comment]
Thank you @netapp-aronk Aron for taking the time to provide feedback on the Enable StorageGrid page.
I will work on this issue with the StorageGrid team as soon as possible.

**Comment by netapp-pcarriga** [comment]
Hi @netapp-aronk, SGRIDDOC-23 has been opened to track this issue and I've added you as watcher.

**Comment by netapp-lhalbert** [comment]
@netapp-aronk: How are these edits? I recommend switching the two paragraphs so the link will be more visible.

The storagegrid-enable documentation site provides examples and cookbooks for evaluating and integrating with StorageGRID.

Go to [How to enable StorageGRID in your environment](https://docs.netapp.com/us-en/storagegrid-enable/index.html) to learn how to test and enable applications in your StorageGRID environment.

**Comment by netapp-lhalbert** [comment]
Shorter still:

[first paragraph as is]

https://docs.netapp.com/us-en/storagegrid-enable/index.html[Learn how to test and enable applications in your StorageGRID environment.].

**Comment by netapp-aronk** [comment]
I think this issue can be closed. Thank you.

**Comment by netapp-maireadn** [comment]
Doc update complete and will be visible in 11.9.
