### ISSUE TITLE
Add page for appliances

### ISSUE THREAD

**Issue by netapp-aronk** [NetAppDocs/storagegrid-117#24]
### Page URL

https://docs.netapp.com/us-en/storagegrid-117/maintain/linux-adding-interfaces-to-existing-node.html

### Page title

Linux: Add Admin or Client interfaces to an existing node

### Summary

we often get asked how to add a client network to nodes in an existing grid. This is a multi-step process involving the change-ip tool and going into maintenance mode to update the interface configurations. Can we please add a page for this?

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-pcarriga** [comment]
Hi @netapp-aronk, I've opened SGRIDDOC-28 to track this doc request, and added you as a watcher.
