### ISSUE TITLE
Use of Proxy to send ASUPs

### ISSUE THREAD

**Issue by beemerdnetapp** [NetAppDocs/storagegrid-117#25]
### Page URL

https://docs.netapp.com/us-en/storagegrid-117/admin/troubleshooting-autosupport-messages.html

### Page title

Troubleshoot AutoSupport messages

### Summary

We had a customer that performed changes on their network and switch. They usually use their proxy to send the ASUPs to. Basically the ASUP goes to their proxy then out to netapp.

Can you please reference this portion of documentation if using a proxy: https://docs.netapp.com/us-en/storagegrid-117/admin/configuring-storage-proxy-settings.html

I would advise in referencing in both configuration of the ASUPs and troubleshooting of ASUPs as well.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-pcarriga** [comment]
Hi @beemerdnetapp, thank you for taking the time to provide this feedback. I will work on this issue with the StorageGrid team and update the documentation accordingly.

**Comment by netapp-pcarriga** [comment]
Hi @beemerdnetapp, the documentation updates are complete and you can view them using the following links:
[Troubleshoot AutoSupport messages](https://docs.netapp.com/us-en/storagegrid-117/admin/troubleshooting-autosupport-messages.html)
[Configure AutoSupport](https://review.docs.netapp.com/us-en/storagegrid-117_main/admin/configure-autosupport-grid-manager.html)
Thanks again for helping us improve our customer documentation.
