### ISSUE TITLE
Mention limit of 500 platform service endpoints per tenant

### ISSUE THREAD

**Issue by vardhanv** [NetAppDocs/storagegrid-117#26]
### Page URL

https://docs.netapp.com/us-en/storagegrid-117/tenant/what-platform-services-are.html

### Page title

What are platform services?

### Summary

Docs today don't mention per tenant limits causing confusion at some customers.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-pcarriga** [comment]
Hi @vardhanv, thank you for taking the time to provide this feedback. I will work on this issue with the StorageGrid team and update the documentation accordingly.

**Comment by netapp-pcarriga** [comment]
Hi @vardhanv, we are not planning to make this update to this version of the documentation site but we will address this issue in future versions. Thanks again for this to our attention and for understanding.
