### ISSUE TITLE
Changes requested by parnter field engineer

### ISSUE THREAD

**Issue by JamieLove-Net2** [NetAppDocs/storagegrid-117#27]
### Page URL

https://docs.netapp.com/us-en/storagegrid-117/sg5700/replacing-e5700sg-controller.html

### Page title

Replace E5700SG controller

### Summary

During a recent SG5712 controller replacement, the partner field engineer encountered some confusion with the documentation. As a result, he requested that one or both changes be considered for the document:

1. Update the TOC to include procedures for both E2800 and E5700SG or group them together.
2. Distinguish between compute and storage controllers in the documentation.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-pcarriga** [comment]
Hi @JamieLove-Net2, thank you for this suggestion. I'll discuss this with the StorageGRID team and update the documentation accordingly.
