### ISSUE TITLE
Add new command to step 6a?

### ISSUE THREAD

**Issue by JamieLove-Net2** [NetAppDocs/storagegrid-117#28]
### Page URL

https://docs.netapp.com/us-en/storagegrid-117/sg100-1000/replacing-services-appliance.html

### Page title

Replace services appliance

### Summary

According to one of our partner field engineers, the following command should be added with the other commands included in step 6a:
'run-host-command ipmitool lan set 1 ipsrc static'

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-pcarriga** [comment]
Hi @JamieLove-Net2, thank you for providing this feedback. I'll consult with the StorageGRID team and update the documentation accordingly.

**Comment by netapp-pcarriga** [comment]
Hi @JamieLove-Net2, we are not planning to make this update to version 11.7 of the documentation site but we will address this issue in future versions. Thanks again for bringing this issue to our attention and for understanding.

**Comment by netapp-pcarriga** [comment]
Hi @JamieLove-Net2, post closure of this issue, this documentation request was published in the StorageGRID 11.7 version. you can view the change on the following pages:
https://docs.netapp.com/us-en/storagegrid-117/sg100-1000/replacing-services-appliance.html
https://docs.netapp.com/us-en/storagegrid-117/sg6000/replacing-sg6000-cn-controller.html
https://docs.netapp.com/us-en/storagegrid-117/sg6100/replace-cmos-in-sgf6112.html#reinstall-the-cmos-battery
https://docs.netapp.com/us-en/storagegrid-117/sg6100/replacing-sgf6112-appliance.html
