### ISSUE TITLE
Syslog missing from list of services/ports

### ISSUE THREAD

**Issue by estarz** [NetAppDocs/storagegrid-117#4]
### Page URL

https://docs.netapp.com/us-en/storagegrid-117/network/external-communications.html

### Page title

External communications

### Summary

Hi,

I believe syslog is missing from the list of ports used for external communications.

Something like from all nodes, to syslog servers, UDP/TCP port 514 should be added, as well as an entry for TCP port 20514 if RELP is selected.

Thanks,
Erik

### Public issues must not contain sensitive information

- [x] This issue contains no sensitive information.

**Comment by netapp-pcarriga** [comment]
Hi @estarz - Thanks for bringing this to our attention. I'll look into it an update the documentation accordingly.

**Comment by netapp-pcarriga** [comment]
Hi @estarz, we have updated the documentation for StorageGRID 11.6 and 11.7 to reflect that the list of ports does not include those used for syslog servers. You can review the changes using the following links:
Version 11.6: [Ports used for external communications](https://docs.netapp.com/us-en/storagegrid-116/network/external-communications.html#port-remapping)
Version 11.7: [Ports used for external communications](https://docs.netapp.com/us-en/storagegrid-117/network/external-communications.html#port-remapping)
Thanks!
