### ISSUE TITLE
Page “Upgrade drive firmware using SANtricity System Manager” has allot space for improvements

### ISSUE THREAD

**Issue by siegfried-h** [NetAppDocs/storagegrid-117#44]
### Page URL

https://docs.netapp.com/us-en/storagegrid-117/sg5700/upgrading-drive-firmware-using-santricity-system-manager.html

### Page title

Upgrade drive firmware using SANtricity System Manager

### Summary

In general this page “Upgrade drive firmware using SANtricity System Manager” has allot space for improvements:
https://docs.netapp.com/us-en/storagegrid-117/sg5700/upgrading-drive-firmware-using-santricity-system-manager.html

Remove thelow statement:
"You have the latest version of SANtricity System Manager installed that is compatible with your StorageGRID version."

I prefer my customer to run 11.70.5P1 instead of the latest 11.80GA. The drive firmware update code hasn’t changed for a long time, no reason to force people to the latest Santricity Version.

It is possible to update SSD’s in SG6060 “online” if you follow the following KB: https://kb.netapp.com/onprem/E-Series/Hardware/E-series_firmware_upgrade_problem_for_the_configured_SSD-Cache_drives
We might want to include the information of this KB in our official SG documentation.

The Drive Update Section of the SG5760 should not talk about SSD’s in SG6060.

Remove the hole section 5 g. No customer will understand what is being said here.

I suggest to create two section for drive firmware update. One for “Offline Drive Firmware update”  and one for “Online Drive Firmware update. Similar like we did for Santricity update, there we also have a page for “Update using Grid Manager” and Update using maintenance mode”. Doing the same would shorten each procedure and makes it more easy to read and understand. If also removed all the IF statements, if you are doing an online update ... IF you are doing and Oflline update

Regards
Siegfried

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-pcarriga** [comment]
HI @siegfried-h, Thank you for these suggestions. I will review them with the StorageGRID team and, if required, make documentation updates.

**Comment by netapp-pcarriga** [comment]
Hi @siegfried-h, we've published the restructured 'Upgrade drive firmware using SANtricity System Manager' content. You can view these changes using the following link:
https://docs.netapp.com/us-en/storagegrid-117/sg6000/upgrading-drive-firmware-using-santricity-system-manager-online.html
Thanks again for helping us improve our customer documentation.
