### ISSUE TITLE
Missing supported RFC details

### ISSUE THREAD

**Issue by ahmadm-netapp** [NetAppDocs/storagegrid-117#9]
### Page URL

https://docs.netapp.com/us-en/storagegrid-117/monitor/considerations-for-external-syslog-server.html

### Page title

Considerations for external syslog server

### Summary

It would be good to include the RFC that StorageGRID uses for syslog implementation. I believe it is RFC 5424.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-pcarriga** [comment]
Hi @ahmadm-netapp, thank you for your recommendation. I'll verify and update the documentation accordingly. Thanks!

**Comment by netapp-pcarriga** [comment]
Hi @ahmadm-netapp, thanks again for this suggestion. At this time we won't update StorgeGRID 11.7 documentation and earlier versions but this recommendation will be considered for inclusion in future versions. Thanks for understanding.
